// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaaoI-JZ_F7psD5F830b_7CwHiLQi1h8g',
    appId: '1:875394948872:android:33dd7bc10f064cb3d716bd',
    messagingSenderId: '875394948872',
    projectId: 'notecloud-nack',
    storageBucket: 'notecloud-nack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPUoQ0ed6eSh44JSM0-gPqWlxysUIJoVo',
    appId: '1:875394948872:ios:18441b2e912d5848d716bd',
    messagingSenderId: '875394948872',
    projectId: 'notecloud-nack',
    storageBucket: 'notecloud-nack.appspot.com',
    androidClientId: '875394948872-v19j8a4uia99b1642c2u0r33r1gpoe38.apps.googleusercontent.com',
    iosClientId: '875394948872-85v886iangdbm4gmg15k2jbo6e2v6q47.apps.googleusercontent.com',
    iosBundleId: 'com.example.notecloud',
  );
}
